version: "3.3"

volumes:
  postgres-data:

services:
  sapper:
    build: ./sapper
    volumes:
      - ./sapper:/usr/src/app
    ports:
      - 80:3000
      - 10000:10000
    command: npm run dev
    environment:
      - AUTH_UUID=${AUTH_UUID}

  posts:
    build: ./posts
    environment:
      - PORT=5000
      - NODE_ENV=development
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: npm run dev
    ports:
      - 5000:5000
    volumes:
      - ./posts:/usr/src/app
      - /usr/src/app/node_modules/

  postgres:
    expose: ["5432"]
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
